//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAESJobs.Client.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenJobs", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OpenJobs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Close_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Job_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_Location_CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_QualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Posting_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Close_Date {
            get {
                return this.Close_DateField;
            }
            set {
                if ((this.Close_DateField.Equals(value) != true)) {
                    this.Close_DateField = value;
                    this.RaisePropertyChanged("Close_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Description {
            get {
                return this.Job_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_DescriptionField, value) != true)) {
                    this.Job_DescriptionField = value;
                    this.RaisePropertyChanged("Job_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Job_ID {
            get {
                return this.Job_IDField;
            }
            set {
                if ((this.Job_IDField.Equals(value) != true)) {
                    this.Job_IDField = value;
                    this.RaisePropertyChanged("Job_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Location {
            get {
                return this.Job_LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_LocationField, value) != true)) {
                    this.Job_LocationField = value;
                    this.RaisePropertyChanged("Job_Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Location_City {
            get {
                return this.Job_Location_CityField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_Location_CityField, value) != true)) {
                    this.Job_Location_CityField = value;
                    this.RaisePropertyChanged("Job_Location_City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Qualification {
            get {
                return this.Job_QualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_QualificationField, value) != true)) {
                    this.Job_QualificationField = value;
                    this.RaisePropertyChanged("Job_Qualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posting_ID {
            get {
                return this.Posting_IDField;
            }
            set {
                if ((this.Posting_IDField.Equals(value) != true)) {
                    this.Posting_IDField = value;
                    this.RaisePropertyChanged("Posting_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreLocations", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class StoreLocations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Location_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Location_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Location_ID {
            get {
                return this.Location_IDField;
            }
            set {
                if ((this.Location_IDField.Equals(value) != true)) {
                    this.Location_IDField = value;
                    this.RaisePropertyChanged("Location_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location_Name {
            get {
                return this.Location_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Location_NameField, value) != true)) {
                    this.Location_NameField = value;
                    this.RaisePropertyChanged("Location_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobTemplates", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class JobTemplates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Job_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_QualificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAESJobs.Client.WebService.Question[] Job_QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Description {
            get {
                return this.Job_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_DescriptionField, value) != true)) {
                    this.Job_DescriptionField = value;
                    this.RaisePropertyChanged("Job_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Job_ID {
            get {
                return this.Job_IDField;
            }
            set {
                if ((this.Job_IDField.Equals(value) != true)) {
                    this.Job_IDField = value;
                    this.RaisePropertyChanged("Job_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Qualifications {
            get {
                return this.Job_QualificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_QualificationsField, value) != true)) {
                    this.Job_QualificationsField = value;
                    this.RaisePropertyChanged("Job_Qualifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAESJobs.Client.WebService.Question[] Job_Questions {
            get {
                return this.Job_QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_QuestionsField, value) != true)) {
                    this.Job_QuestionsField = value;
                    this.RaisePropertyChanged("Job_Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullQuestion {
            get {
                return this.FullQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.FullQuestionField, value) != true)) {
                    this.FullQuestionField = value;
                    this.RaisePropertyChanged("FullQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionTitle {
            get {
                return this.QuestionTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTitleField, value) != true)) {
                    this.QuestionTitleField = value;
                    this.RaisePropertyChanged("QuestionTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionForm", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class QuestionForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool checkedQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAESJobs.Client.WebService.Question questionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool checkedQuestion {
            get {
                return this.checkedQuestionField;
            }
            set {
                if ((this.checkedQuestionField.Equals(value) != true)) {
                    this.checkedQuestionField = value;
                    this.RaisePropertyChanged("checkedQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAESJobs.Client.WebService.Question question {
            get {
                return this.questionField;
            }
            set {
                if ((object.ReferenceEquals(this.questionField, value) != true)) {
                    this.questionField = value;
                    this.RaisePropertyChanged("question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job_Application", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService")]
    [System.SerializableAttribute()]
    public partial class Job_Application : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicantID {
            get {
                return this.ApplicantIDField;
            }
            set {
                if ((this.ApplicantIDField.Equals(value) != true)) {
                    this.ApplicantIDField = value;
                    this.RaisePropertyChanged("ApplicantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicantName {
            get {
                return this.ApplicantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantNameField, value) != true)) {
                    this.ApplicantNameField = value;
                    this.RaisePropertyChanged("ApplicantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobID {
            get {
                return this.JobIDField;
            }
            set {
                if ((this.JobIDField.Equals(value) != true)) {
                    this.JobIDField = value;
                    this.RaisePropertyChanged("JobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stage {
            get {
                return this.StageField;
            }
            set {
                if ((this.StageField.Equals(value) != true)) {
                    this.StageField = value;
                    this.RaisePropertyChanged("Stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question_Answer", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService")]
    [System.SerializableAttribute()]
    public partial class Question_Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPosting", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class NewPosting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Close_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Job_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Location_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Close_Date {
            get {
                return this.Close_DateField;
            }
            set {
                if ((this.Close_DateField.Equals(value) != true)) {
                    this.Close_DateField = value;
                    this.RaisePropertyChanged("Close_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Job_ID {
            get {
                return this.Job_IDField;
            }
            set {
                if ((this.Job_IDField.Equals(value) != true)) {
                    this.Job_IDField = value;
                    this.RaisePropertyChanged("Job_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Location_ID {
            get {
                return this.Location_IDField;
            }
            set {
                if ((this.Location_IDField.Equals(value) != true)) {
                    this.Location_IDField = value;
                    this.RaisePropertyChanged("Location_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionIDJobID", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class QuestionIDJobID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Job_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Job_ID {
            get {
                return this.Job_IDField;
            }
            set {
                if ((this.Job_IDField.Equals(value) != true)) {
                    this.Job_IDField = value;
                    this.RaisePropertyChanged("Job_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer_TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Application_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Question_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer_Text {
            get {
                return this.Answer_TextField;
            }
            set {
                if ((object.ReferenceEquals(this.Answer_TextField, value) != true)) {
                    this.Answer_TextField = value;
                    this.RaisePropertyChanged("Answer_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Application_ID {
            get {
                return this.Application_IDField;
            }
            set {
                if ((this.Application_IDField.Equals(value) != true)) {
                    this.Application_IDField = value;
                    this.RaisePropertyChanged("Application_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Question_ID {
            get {
                return this.Question_IDField;
            }
            set {
                if ((this.Question_IDField.Equals(value) != true)) {
                    this.Question_IDField = value;
                    this.RaisePropertyChanged("Question_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Posting_List", ReplyAction="http://tempuri.org/IJobService/Get_Job_Posting_ListResponse")]
        WcfAESJobs.Client.WebService.OpenJobs[] Get_Job_Posting_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Posting_List", ReplyAction="http://tempuri.org/IJobService/Get_Job_Posting_ListResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.OpenJobs[]> Get_Job_Posting_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Posting_By_ID", ReplyAction="http://tempuri.org/IJobService/Get_Posting_By_IDResponse")]
        WcfAESJobs.Client.WebService.OpenJobs Get_Posting_By_ID(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Posting_By_ID", ReplyAction="http://tempuri.org/IJobService/Get_Posting_By_IDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.OpenJobs> Get_Posting_By_IDAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Store_Location_List", ReplyAction="http://tempuri.org/IJobService/Get_Store_Location_ListResponse")]
        WcfAESJobs.Client.WebService.StoreLocations[] Get_Store_Location_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Store_Location_List", ReplyAction="http://tempuri.org/IJobService/Get_Store_Location_ListResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.StoreLocations[]> Get_Store_Location_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Template_List", ReplyAction="http://tempuri.org/IJobService/Get_Job_Template_ListResponse")]
        WcfAESJobs.Client.WebService.JobTemplates[] Get_Job_Template_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Template_List", ReplyAction="http://tempuri.org/IJobService/Get_Job_Template_ListResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.JobTemplates[]> Get_Job_Template_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_JobTemplate_By_ID", ReplyAction="http://tempuri.org/IJobService/Get_JobTemplate_By_IDResponse")]
        WcfAESJobs.Client.WebService.JobTemplates Get_JobTemplate_By_ID(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_JobTemplate_By_ID", ReplyAction="http://tempuri.org/IJobService/Get_JobTemplate_By_IDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.JobTemplates> Get_JobTemplate_By_IDAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Question_Form", ReplyAction="http://tempuri.org/IJobService/Get_Question_FormResponse")]
        WcfAESJobs.Client.WebService.QuestionForm[] Get_Question_Form(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Question_Form", ReplyAction="http://tempuri.org/IJobService/Get_Question_FormResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.QuestionForm[]> Get_Question_FormAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_PreApp_Questions", ReplyAction="http://tempuri.org/IJobService/Get_PreApp_QuestionsResponse")]
        WcfAESJobs.Client.WebService.Question[] Get_PreApp_Questions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_PreApp_Questions", ReplyAction="http://tempuri.org/IJobService/Get_PreApp_QuestionsResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question[]> Get_PreApp_QuestionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Application_By_ID", ReplyAction="http://tempuri.org/IJobService/Get_Job_Application_By_IDResponse")]
        WcfAESJobs.Client.WebService.Job_Application Get_Job_Application_By_ID(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Application_By_ID", ReplyAction="http://tempuri.org/IJobService/Get_Job_Application_By_IDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Job_Application> Get_Job_Application_By_IDAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Application_List_By_Stage", ReplyAction="http://tempuri.org/IJobService/Get_Job_Application_List_By_StageResponse")]
        WcfAESJobs.Client.WebService.Job_Application[] Get_Job_Application_List_By_Stage(System.Nullable<int> stage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Job_Application_List_By_Stage", ReplyAction="http://tempuri.org/IJobService/Get_Job_Application_List_By_StageResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Job_Application[]> Get_Job_Application_List_By_StageAsync(System.Nullable<int> stage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Answers_By_Application_ID", ReplyAction="http://tempuri.org/IJobService/Get_Answers_By_Application_IDResponse")]
        WcfAESJobs.Client.WebService.Question_Answer[] Get_Answers_By_Application_ID(System.Nullable<int> Application_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Get_Answers_By_Application_ID", ReplyAction="http://tempuri.org/IJobService/Get_Answers_By_Application_IDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question_Answer[]> Get_Answers_By_Application_IDAsync(System.Nullable<int> Application_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Create_Job_Posting", ReplyAction="http://tempuri.org/IJobService/Create_Job_PostingResponse")]
        void Create_Job_Posting(WcfAESJobs.Client.WebService.NewPosting posting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Create_Job_Posting", ReplyAction="http://tempuri.org/IJobService/Create_Job_PostingResponse")]
        System.Threading.Tasks.Task Create_Job_PostingAsync(WcfAESJobs.Client.WebService.NewPosting posting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Create_Job_Template", ReplyAction="http://tempuri.org/IJobService/Create_Job_TemplateResponse")]
        void Create_Job_Template(WcfAESJobs.Client.WebService.JobTemplates newJob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Create_Job_Template", ReplyAction="http://tempuri.org/IJobService/Create_Job_TemplateResponse")]
        System.Threading.Tasks.Task Create_Job_TemplateAsync(WcfAESJobs.Client.WebService.JobTemplates newJob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Create_Application", ReplyAction="http://tempuri.org/IJobService/Create_ApplicationResponse")]
        int Create_Application(string UserID, int Posting_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Create_Application", ReplyAction="http://tempuri.org/IJobService/Create_ApplicationResponse")]
        System.Threading.Tasks.Task<int> Create_ApplicationAsync(string UserID, int Posting_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Delete_Job_Posting", ReplyAction="http://tempuri.org/IJobService/Delete_Job_PostingResponse")]
        void Delete_Job_Posting(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Delete_Job_Posting", ReplyAction="http://tempuri.org/IJobService/Delete_Job_PostingResponse")]
        System.Threading.Tasks.Task Delete_Job_PostingAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Delete_Job_Template", ReplyAction="http://tempuri.org/IJobService/Delete_Job_TemplateResponse")]
        void Delete_Job_Template(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Delete_Job_Template", ReplyAction="http://tempuri.org/IJobService/Delete_Job_TemplateResponse")]
        System.Threading.Tasks.Task Delete_Job_TemplateAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/getQuestionsByJobID", ReplyAction="http://tempuri.org/IJobService/getQuestionsByJobIDResponse")]
        WcfAESJobs.Client.WebService.Question[] getQuestionsByJobID(System.Nullable<int> JobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/getQuestionsByJobID", ReplyAction="http://tempuri.org/IJobService/getQuestionsByJobIDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question[]> getQuestionsByJobIDAsync(System.Nullable<int> JobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/getQuestionByID", ReplyAction="http://tempuri.org/IJobService/getQuestionByIDResponse")]
        WcfAESJobs.Client.WebService.Question getQuestionByID(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/getQuestionByID", ReplyAction="http://tempuri.org/IJobService/getQuestionByIDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question> getQuestionByIDAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/deleteQuestionByID", ReplyAction="http://tempuri.org/IJobService/deleteQuestionByIDResponse")]
        void deleteQuestionByID(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/deleteQuestionByID", ReplyAction="http://tempuri.org/IJobService/deleteQuestionByIDResponse")]
        System.Threading.Tasks.Task deleteQuestionByIDAsync(System.Nullable<int> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/getAllQuestions", ReplyAction="http://tempuri.org/IJobService/getAllQuestionsResponse")]
        WcfAESJobs.Client.WebService.Question[] getAllQuestions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/getAllQuestions", ReplyAction="http://tempuri.org/IJobService/getAllQuestionsResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question[]> getAllQuestionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/addNewQuestion", ReplyAction="http://tempuri.org/IJobService/addNewQuestionResponse")]
        void addNewQuestion(WcfAESJobs.Client.WebService.Question question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/addNewQuestion", ReplyAction="http://tempuri.org/IJobService/addNewQuestionResponse")]
        System.Threading.Tasks.Task addNewQuestionAsync(WcfAESJobs.Client.WebService.Question question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/addNewPreAppQuestion", ReplyAction="http://tempuri.org/IJobService/addNewPreAppQuestionResponse")]
        void addNewPreAppQuestion(WcfAESJobs.Client.WebService.Question question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/addNewPreAppQuestion", ReplyAction="http://tempuri.org/IJobService/addNewPreAppQuestionResponse")]
        System.Threading.Tasks.Task addNewPreAppQuestionAsync(WcfAESJobs.Client.WebService.Question question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/addQuestionToJob", ReplyAction="http://tempuri.org/IJobService/addQuestionToJobResponse")]
        void addQuestionToJob(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/addQuestionToJob", ReplyAction="http://tempuri.org/IJobService/addQuestionToJobResponse")]
        System.Threading.Tasks.Task addQuestionToJobAsync(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/removeQuestionFromJob", ReplyAction="http://tempuri.org/IJobService/removeQuestionFromJobResponse")]
        void removeQuestionFromJob(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/removeQuestionFromJob", ReplyAction="http://tempuri.org/IJobService/removeQuestionFromJobResponse")]
        System.Threading.Tasks.Task removeQuestionFromJobAsync(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Add_Answer_To_Table", ReplyAction="http://tempuri.org/IJobService/Add_Answer_To_TableResponse")]
        void Add_Answer_To_Table(WcfAESJobs.Client.WebService.Answer[] answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Add_Answer_To_Table", ReplyAction="http://tempuri.org/IJobService/Add_Answer_To_TableResponse")]
        System.Threading.Tasks.Task Add_Answer_To_TableAsync(WcfAESJobs.Client.WebService.Answer[] answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Job_Template", ReplyAction="http://tempuri.org/IJobService/Update_Job_TemplateResponse")]
        void Update_Job_Template(WcfAESJobs.Client.WebService.JobTemplates jobTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Job_Template", ReplyAction="http://tempuri.org/IJobService/Update_Job_TemplateResponse")]
        System.Threading.Tasks.Task Update_Job_TemplateAsync(WcfAESJobs.Client.WebService.JobTemplates jobTemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Question", ReplyAction="http://tempuri.org/IJobService/Update_QuestionResponse")]
        void Update_Question(WcfAESJobs.Client.WebService.Question question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Question", ReplyAction="http://tempuri.org/IJobService/Update_QuestionResponse")]
        System.Threading.Tasks.Task Update_QuestionAsync(WcfAESJobs.Client.WebService.Question question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Job_Questions_By_Form", ReplyAction="http://tempuri.org/IJobService/Update_Job_Questions_By_FormResponse")]
        void Update_Job_Questions_By_Form(int Job_ID, WcfAESJobs.Client.WebService.QuestionForm[] form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Job_Questions_By_Form", ReplyAction="http://tempuri.org/IJobService/Update_Job_Questions_By_FormResponse")]
        System.Threading.Tasks.Task Update_Job_Questions_By_FormAsync(int Job_ID, WcfAESJobs.Client.WebService.QuestionForm[] form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Application_Stage", ReplyAction="http://tempuri.org/IJobService/Update_Application_StageResponse")]
        void Update_Application_Stage(System.Nullable<int> Application_ID, int stage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/Update_Application_Stage", ReplyAction="http://tempuri.org/IJobService/Update_Application_StageResponse")]
        System.Threading.Tasks.Task Update_Application_StageAsync(System.Nullable<int> Application_ID, int stage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : WcfAESJobs.Client.WebService.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<WcfAESJobs.Client.WebService.IJobService>, WcfAESJobs.Client.WebService.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfAESJobs.Client.WebService.OpenJobs[] Get_Job_Posting_List() {
            return base.Channel.Get_Job_Posting_List();
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.OpenJobs[]> Get_Job_Posting_ListAsync() {
            return base.Channel.Get_Job_Posting_ListAsync();
        }
        
        public WcfAESJobs.Client.WebService.OpenJobs Get_Posting_By_ID(System.Nullable<int> value) {
            return base.Channel.Get_Posting_By_ID(value);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.OpenJobs> Get_Posting_By_IDAsync(System.Nullable<int> value) {
            return base.Channel.Get_Posting_By_IDAsync(value);
        }
        
        public WcfAESJobs.Client.WebService.StoreLocations[] Get_Store_Location_List() {
            return base.Channel.Get_Store_Location_List();
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.StoreLocations[]> Get_Store_Location_ListAsync() {
            return base.Channel.Get_Store_Location_ListAsync();
        }
        
        public WcfAESJobs.Client.WebService.JobTemplates[] Get_Job_Template_List() {
            return base.Channel.Get_Job_Template_List();
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.JobTemplates[]> Get_Job_Template_ListAsync() {
            return base.Channel.Get_Job_Template_ListAsync();
        }
        
        public WcfAESJobs.Client.WebService.JobTemplates Get_JobTemplate_By_ID(System.Nullable<int> value) {
            return base.Channel.Get_JobTemplate_By_ID(value);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.JobTemplates> Get_JobTemplate_By_IDAsync(System.Nullable<int> value) {
            return base.Channel.Get_JobTemplate_By_IDAsync(value);
        }
        
        public WcfAESJobs.Client.WebService.QuestionForm[] Get_Question_Form(System.Nullable<int> value) {
            return base.Channel.Get_Question_Form(value);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.QuestionForm[]> Get_Question_FormAsync(System.Nullable<int> value) {
            return base.Channel.Get_Question_FormAsync(value);
        }
        
        public WcfAESJobs.Client.WebService.Question[] Get_PreApp_Questions() {
            return base.Channel.Get_PreApp_Questions();
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question[]> Get_PreApp_QuestionsAsync() {
            return base.Channel.Get_PreApp_QuestionsAsync();
        }
        
        public WcfAESJobs.Client.WebService.Job_Application Get_Job_Application_By_ID(System.Nullable<int> value) {
            return base.Channel.Get_Job_Application_By_ID(value);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Job_Application> Get_Job_Application_By_IDAsync(System.Nullable<int> value) {
            return base.Channel.Get_Job_Application_By_IDAsync(value);
        }
        
        public WcfAESJobs.Client.WebService.Job_Application[] Get_Job_Application_List_By_Stage(System.Nullable<int> stage) {
            return base.Channel.Get_Job_Application_List_By_Stage(stage);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Job_Application[]> Get_Job_Application_List_By_StageAsync(System.Nullable<int> stage) {
            return base.Channel.Get_Job_Application_List_By_StageAsync(stage);
        }
        
        public WcfAESJobs.Client.WebService.Question_Answer[] Get_Answers_By_Application_ID(System.Nullable<int> Application_ID) {
            return base.Channel.Get_Answers_By_Application_ID(Application_ID);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question_Answer[]> Get_Answers_By_Application_IDAsync(System.Nullable<int> Application_ID) {
            return base.Channel.Get_Answers_By_Application_IDAsync(Application_ID);
        }
        
        public void Create_Job_Posting(WcfAESJobs.Client.WebService.NewPosting posting) {
            base.Channel.Create_Job_Posting(posting);
        }
        
        public System.Threading.Tasks.Task Create_Job_PostingAsync(WcfAESJobs.Client.WebService.NewPosting posting) {
            return base.Channel.Create_Job_PostingAsync(posting);
        }
        
        public void Create_Job_Template(WcfAESJobs.Client.WebService.JobTemplates newJob) {
            base.Channel.Create_Job_Template(newJob);
        }
        
        public System.Threading.Tasks.Task Create_Job_TemplateAsync(WcfAESJobs.Client.WebService.JobTemplates newJob) {
            return base.Channel.Create_Job_TemplateAsync(newJob);
        }
        
        public int Create_Application(string UserID, int Posting_ID) {
            return base.Channel.Create_Application(UserID, Posting_ID);
        }
        
        public System.Threading.Tasks.Task<int> Create_ApplicationAsync(string UserID, int Posting_ID) {
            return base.Channel.Create_ApplicationAsync(UserID, Posting_ID);
        }
        
        public void Delete_Job_Posting(System.Nullable<int> value) {
            base.Channel.Delete_Job_Posting(value);
        }
        
        public System.Threading.Tasks.Task Delete_Job_PostingAsync(System.Nullable<int> value) {
            return base.Channel.Delete_Job_PostingAsync(value);
        }
        
        public void Delete_Job_Template(System.Nullable<int> value) {
            base.Channel.Delete_Job_Template(value);
        }
        
        public System.Threading.Tasks.Task Delete_Job_TemplateAsync(System.Nullable<int> value) {
            return base.Channel.Delete_Job_TemplateAsync(value);
        }
        
        public WcfAESJobs.Client.WebService.Question[] getQuestionsByJobID(System.Nullable<int> JobID) {
            return base.Channel.getQuestionsByJobID(JobID);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question[]> getQuestionsByJobIDAsync(System.Nullable<int> JobID) {
            return base.Channel.getQuestionsByJobIDAsync(JobID);
        }
        
        public WcfAESJobs.Client.WebService.Question getQuestionByID(System.Nullable<int> value) {
            return base.Channel.getQuestionByID(value);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question> getQuestionByIDAsync(System.Nullable<int> value) {
            return base.Channel.getQuestionByIDAsync(value);
        }
        
        public void deleteQuestionByID(System.Nullable<int> value) {
            base.Channel.deleteQuestionByID(value);
        }
        
        public System.Threading.Tasks.Task deleteQuestionByIDAsync(System.Nullable<int> value) {
            return base.Channel.deleteQuestionByIDAsync(value);
        }
        
        public WcfAESJobs.Client.WebService.Question[] getAllQuestions() {
            return base.Channel.getAllQuestions();
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.WebService.Question[]> getAllQuestionsAsync() {
            return base.Channel.getAllQuestionsAsync();
        }
        
        public void addNewQuestion(WcfAESJobs.Client.WebService.Question question) {
            base.Channel.addNewQuestion(question);
        }
        
        public System.Threading.Tasks.Task addNewQuestionAsync(WcfAESJobs.Client.WebService.Question question) {
            return base.Channel.addNewQuestionAsync(question);
        }
        
        public void addNewPreAppQuestion(WcfAESJobs.Client.WebService.Question question) {
            base.Channel.addNewPreAppQuestion(question);
        }
        
        public System.Threading.Tasks.Task addNewPreAppQuestionAsync(WcfAESJobs.Client.WebService.Question question) {
            return base.Channel.addNewPreAppQuestionAsync(question);
        }
        
        public void addQuestionToJob(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID) {
            base.Channel.addQuestionToJob(questionIDjobID);
        }
        
        public System.Threading.Tasks.Task addQuestionToJobAsync(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID) {
            return base.Channel.addQuestionToJobAsync(questionIDjobID);
        }
        
        public void removeQuestionFromJob(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID) {
            base.Channel.removeQuestionFromJob(questionIDjobID);
        }
        
        public System.Threading.Tasks.Task removeQuestionFromJobAsync(WcfAESJobs.Client.WebService.QuestionIDJobID questionIDjobID) {
            return base.Channel.removeQuestionFromJobAsync(questionIDjobID);
        }
        
        public void Add_Answer_To_Table(WcfAESJobs.Client.WebService.Answer[] answer) {
            base.Channel.Add_Answer_To_Table(answer);
        }
        
        public System.Threading.Tasks.Task Add_Answer_To_TableAsync(WcfAESJobs.Client.WebService.Answer[] answer) {
            return base.Channel.Add_Answer_To_TableAsync(answer);
        }
        
        public void Update_Job_Template(WcfAESJobs.Client.WebService.JobTemplates jobTemp) {
            base.Channel.Update_Job_Template(jobTemp);
        }
        
        public System.Threading.Tasks.Task Update_Job_TemplateAsync(WcfAESJobs.Client.WebService.JobTemplates jobTemp) {
            return base.Channel.Update_Job_TemplateAsync(jobTemp);
        }
        
        public void Update_Question(WcfAESJobs.Client.WebService.Question question) {
            base.Channel.Update_Question(question);
        }
        
        public System.Threading.Tasks.Task Update_QuestionAsync(WcfAESJobs.Client.WebService.Question question) {
            return base.Channel.Update_QuestionAsync(question);
        }
        
        public void Update_Job_Questions_By_Form(int Job_ID, WcfAESJobs.Client.WebService.QuestionForm[] form) {
            base.Channel.Update_Job_Questions_By_Form(Job_ID, form);
        }
        
        public System.Threading.Tasks.Task Update_Job_Questions_By_FormAsync(int Job_ID, WcfAESJobs.Client.WebService.QuestionForm[] form) {
            return base.Channel.Update_Job_Questions_By_FormAsync(Job_ID, form);
        }
        
        public void Update_Application_Stage(System.Nullable<int> Application_ID, int stage) {
            base.Channel.Update_Application_Stage(Application_ID, stage);
        }
        
        public System.Threading.Tasks.Task Update_Application_StageAsync(System.Nullable<int> Application_ID, int stage) {
            return base.Channel.Update_Application_StageAsync(Application_ID, stage);
        }
    }
}
