//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAESJobsWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationTable()
        {
            this.AnswerTables = new HashSet<AnswerTable>();
        }
    
        public int Id { get; set; }
        public int JobID { get; set; }
        public int ApplicantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerTable> AnswerTables { get; set; }
        public virtual ApplicantTable Applicant { get; set; }
        public virtual AvailableJob AvailableJob { get; set; }
    }
}
